# Generated by Django 3.0.5 on 2020-04-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatus',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='char',
            new_name='city',
        ),
    ]
